#!/bin/bash

if [ -z "$1" ] ; then
    echo "You need to specify at least one program argument:"
    echo "1. Path to the PHP project to parse. Optional: 2. The graph database id, default is 1. If multiple neo4j instances are installed, then you can also use other IDs like 2, 3 etc."
    exit
fi

if [ -z "$2" ] ; then
    # Second argument was not given, default ID to 1.
    appendix=1
else
    appendix=$2
fi

function readVal {
    while read p; do
        key=$(echo $p | cut -f1 -d=)
        path=$(echo $p | cut -f2 -d=)

        if [ $key = $2 ] ; then
            echo "$path"
        fi
    done < $1
}

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_FILE=$THIS_SCRIPT_DIR/../config
RESULT_PATH=$THIS_SCRIPT_DIR/parse_results
PATH_PHP7=$(readVal $CONFIG_FILE "php7")
PHPJOERN=$(readVal $CONFIG_FILE "phpjoern")

if [ -z "$PHP7" ]; then
    PHP7=${PATH_PHP7}/usr/bin/php
fi

path_to_parse=$1

$PHP7 $PHPJOERN/src/Parser.php -a "$appendix" -f jexp "$path_to_parse"

mv nodes.csv${appendix} $RESULT_PATH
mv rels.csv${appendix} $RESULT_PATH
